### ISSUE TITLE
我在使用sdk的时候报错， uuid.NewV4 有两个返回值，使用的时候没有接收error导致编译不通过

### ISSUE THREAD

**Issue by YJY12138** [volcengine/apminsight-server-sdk-go#7]
../../go/pkg/mod/github.com/volcengine/apminsight-server-sdk-go@v1.1.1/trace/aitracer/tracer.go:84:16: assignment mismatch: 1 variable but uuid.NewV4 returns 2 values

**Comment by guyifan2018** [comment]
has been fixed
